baseurl = "https://example.org/"
title = "Caf√© Alpenblick Saas-Fee"
theme = "arabica"

[params]
    description = "Essen Trinken Geniessen"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
